[package]
name = "idno_std"
version = "0.2.0"
edition = "2024"

[features]
# Test binaries can create more simultaneously live thread contexts than the
# game does in production.
many-test-threads = []

[dependencies]
bitfield.workspace = true
glam.workspace = true
hashbrown.workspace = true
log = { workspace = true, features = ["std"] }
micropool.workspace = true
profiling.workspace = true
rapidhash.workspace = true
